# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
