# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='insta_user',
            new_name='user',
        ),
    ]
